In [1]:
import numpy as np
import scipy.io
import pydot
import graphviz
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.tree import export_graphviz
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.cross_validation import cross_val_score
from sklearn.ensemble import AdaBoostClassifier

In [2]:
data_combined = pd.read_csv("/Users/apple/Documents/Hackthon/Suncode 2018/suncode/data_v2_sample.csv")

In [3]:
def get_importance(rf):
    # Get numerical feature importances
    importances = list(rf.feature_importances_)
    # List of tuples with variable and importance
    feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]
    # Sort the feature importances by most important first
    feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
    # Print out the feature and importances 
    for pair in feature_importances:
        print('Variable: {:20} Importance: {}'.format(*pair))

In [4]:
def get_graph(rf):
    # Pull out one tree from the forest
    tree = rf.estimators_[np.random.choice(len(rf.estimators_))]
    # Export the image to a dot file
    # export_graphviz(tree, out_file = 'tree.dot', feature_names = feature_list, rounded = True, precision = 1)
    export_graphviz(tree, out_file = 'tree.dot', feature_names = feature_list, rounded = True)
    # Use dot file to create a graph
    (graph, ) = pydot.graph_from_dot_file('tree.dot')
    # Write graph to a png file
    graph.write_png('tree.png')

In [5]:
data_combined = data_combined.drop('Unnamed: 0',axis=1)
data_combined = data_combined.drop('JobId',axis=1)
# data_combined = data_combined.drop('State',axis=1)
# data_combined = data_combined.drop('GasRatePlanID',axis=1)
# data_combined = data_combined.drop('UtilityRatePlanId',axis=1)
data_combined = data_combined.drop('PowerwallCount',axis=1)
# data_combined = data_combined.drop('MPU',axis=1)
# data_combined = data_combined.drop('Reroof',axis=1)

In [12]:
data_combined.columns

Index([u'EngineeringSoldkWSize', u'EngineeringSoldAnnualkWh',
       u'EnergyConsumption', u'State', u'Zip', u'AHJ', u'RoofType',
       u'RoofSqFoot', u'NumMountingPlanes', u'NumPanels', u'Utility',
       u'ProductTypeAlt', u'UtilityCostPerKWh', u'OldBill',
       u'UtilityRatePlanId', u'UtilityInflationRate', u'GasRatePlanID',
       u'AverageShading', u'NumStories', u'Status'],
      dtype='object')

In [13]:
desc_list = ['State', 'Zip', 'AHJ', 'RoofType', 'Utility', 'ProductTypeAlt', 
             'UtilityRatePlanId', 'GasRatePlanID', 'NumStories']
# 'Region'
frame = list()
for indx, col_name in enumerate(desc_list):
    temp = pd.get_dummies(data_combined[col_name])
    data_combined = data_combined.drop(col_name, axis=1)
    frame.append(temp)
frame = [data_combined] + frame
data_combined = pd.concat(frame, axis=1)
    
# temp1 = pd.get_dummies(data_combined['UtilityRatePlanId'])
# temp2 = pd.get_dummies(data_combined['GasRatePlanID'])
# temp3 = pd.get_dummies(data_combined['State'])
# temp4 = 
# data_combined = data_combined.drop('UtilityRatePlanId',axis=1)
# data_combined = data_combined.drop('GasRatePlanID',axis=1)
# data_combined = data_combined.drop('State',axis=1)
# frame = [data_combined, temp1, temp2, temp3]
# data_combined = pd.concat(frame, axis=1)

In [15]:
data_combined

,EngineeringSoldkWSize,EngineeringSoldAnnualkWh,EnergyConsumption,RoofSqFoot,NumMountingPlanes,NumPanels,UtilityCostPerKWh,OldBill,UtilityInflationRate,AverageShading,...,50090.0,90398.0,100099.0,998377099.0,998467098.0,998469099.0,998504099.0,Above Two Stories,One Story,Two Stories
0,3.465,3806.0090,8860.0,1508.0,1,11,0.113579,134.1167,0.0380,1.200000e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,13.860,18115.3150,62233.0,2518.0,4,44,0.193729,1056.3469,0.0290,4.363636e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,3.780,4887.0342,7464.0,1980.0,3,12,0.152606,146.5714,0.0290,1.708333e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,16.065,23229.5524,23834.0,3155.0,3,51,0.330294,704.0654,0.0290,8.823529e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10.920,14676.4759,18131.0,6512.0,2,42,0.298678,499.3237,0.0290,8.571429e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,4.095,4089.5730,6483.0,NaN,2,13,0.203558,158.0187,0.0290,3.430769e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,6.500,8025.7797,8094.0,3673.0,2,25,0.185493,170.7077,0.0290,9.304348e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8.505,12196.6609,12409.0,2976.0,2,27,0.264252,321.3057,0.0290,5.312500e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,5.035,6701.9949,8706.0,2515.0,3,19,0.178033,177.2094,0.0290,6.684210e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,3.190,4972.2416,6270.0,2672.0,1,11,0.215150,162.0934,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10,6.760,9105.3562,6073.0,3808.0,3,26,0.221312,161.6801,0.0290,1.384615e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12.285,17330.0570,14083.0,5085.0,3,39,0.297326,396.2484,0.0290,5.076923e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,4.940,7258.3906,7737.0,3313.0,1,19,0.240437,202.3337,0.0290,3.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13,5.670,8232.7560,7759.0,2050.0,2,18,0.213104,185.8362,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14,3.120,4796.0282,5782.0,2687.0,1,12,0.204045,145.6279,0.0290,7.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,3.780,4564.8981,3232.0,2360.0,1,12,0.183530,96.7428,0.0290,2.500000e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,4.420,6145.4131,6179.0,NaN,1,17,0.228446,165.6774,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,5.200,7962.6714,7893.0,3085.0,1,20,0.204619,182.6349,0.0290,6.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,9.360,10211.3899,10468.0,2823.0,2,36,0.249508,265.7006,0.0290,2.191667e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,11.960,17779.8213,18021.0,3424.0,1,46,0.242077,411.5859,0.0290,1.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,3.380,5426.3984,7011.0,1779.0,1,13,0.183319,155.1507,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,7.540,11101.8507,12372.0,2211.0,3,29,0.125626,187.4399,0.0350,3.793103e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
22,8.320,13414.6050,13843.0,1898.0,1,32,0.124223,201.2214,0.0350,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,6.300,6945.7718,10579.0,3266.0,1,20,0.125500,168.5582,0.0350,2.900000e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,5.830,7876.8480,13876.0,4080.0,3,22,0.123423,200.6377,0.0350,1.345455e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,6.500,9806.5233,9814.0,2241.0,1,25,0.157797,129.0520,0.0350,4.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,4.420,6611.9272,6683.0,2048.0,1,17,0.156157,146.0058,0.0350,6.250000e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,10.400,11638.5966,18696.0,2573.0,3,40,0.130556,256.2393,0.0190,1.640000e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
28,8.060,10895.4147,13630.0,2228.0,2,31,0.136676,208.0739,0.0190,1.110000e-16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
29,9.880,9913.7115,18068.0,3600.0,3,38,0.226433,393.7659,0.0190,2.905263e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19970,2.600,3016.1384,5379.0,1431.0,1,8,0.226230,169.5335,0.0330,1.700000e-01,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19971,6.300,7530.9149,3534.0,2126.0,2,21,0.244855,72.1099,0.0330,7.428571e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19972,6.175,6965.1098,7220.0,1546.0,2,19,0.218361,199.5061,0.0330,0.000000e+00,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19973,4.800,6074.7440,6000.0,1124.0,1,16,0.195307,149.4517,0.0350,3.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19974,4.500,3504.2617,3985.0,1653.0,1,15,0.192480,115.7179,0.0350,3.638462e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
19975,6.825,9043.2696,1961.0,2248.0,2,21,0.289051,47.2358,0.0540,-2.220000e-16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19976,6.600,6777.6014,7116.0,1814.0,2,22,0.203592,172.5285,0.0540,9.545455e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19977,6.900,6398.4374,7590.0,3202.0,1,23,0.225615,142.7016,0.0290,1.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19978,4.200,5372.9069,5464.0,2140.0,1,14,0.185564,138.4517,0.0372,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19979,4.550,3805.8178,7491.0,1161.0,2,14,0.219350,188.7276,0.0400,2.728571e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19980,6.300,7359.8484,7177.0,2008.0,1,21,0.219655,183.1703,0.0400,1.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19981,3.900,4313.5776,12286.0,1508.0,3,12,0.216322,273.2764,0.0400,3.083333e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19982,5.400,8246.3844,8973.0,2569.0,2,18,0.255705,240.8811,0.0290,5.000000e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19983,15.300,16420.0074,28315.0,7582.0,3,51,0.323261,810.0727,0.0290,1.029412e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19984,7.800,11158.5333,9405.0,2446.0,2,24,0.272656,264.1292,0.0290,6.750000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19985,6.300,8092.6628,7759.0,2355.0,1,21,0.266938,223.0326,0.0290,2.100000e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19986,4.875,6676.7984,6477.0,1974.0,2,15,0.244269,181.7585,0.0290,4.200000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
19987,5.200,8086.0211,7739.0,2246.0,2,16,0.238332,153.7041,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19988,6.500,11023.3981,9207.0,3671.0,2,20,0.244357,187.4828,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19989,2.100,3158.4299,3179.0,3357.0,1,7,0.210778,55.8387,0.0290,1.585714e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19990,15.900,22973.4024,24190.0,7017.0,5,53,0.327962,711.0314,0.0290,1.830189e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19991,3.900,6353.3810,3837.0,2908.0,1,12,0.227667,122.7107,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19992,13.325,20839.8881,21034.0,2847.0,3,41,0.283482,544.9438,0.0290,2.243902e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19993,12.675,15304.5161,25244.0,3525.0,5,39,0.313400,706.6007,0.0290,6.282051e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19994,4.875,6432.2248,7473.0,1546.0,2,15,0.229478,190.9544,0.0290,4.333333e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19995,5.850,8993.4713,7354.0,1946.0,3,18,0.249353,202.7260,0.0290,6.833333e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
19996,15.275,20416.4615,28250.0,6843.0,5,47,0.205299,530.6196,0.0290,4.425532e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19997,6.500,9085.0457,9427.0,3243.0,1,20,0.099264,77.9804,0.0290,8.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19998,15.900,16110.6959,22092.0,2160.0,7,53,0.131961,242.9398,0.0337,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19999,6.500,7114.5657,9225.0,1379.0,3,20,0.201033,154.5442,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
data_combined.shape

(20000, 6292)

In [9]:
# # One-hot encode the data using pandas get_dummies
# data_combined = pd.get_dummies(data_combined)
# # Display the first 5 rows of the last 12 columns
# data_combined.iloc[:,5:].head(5)

In [17]:
# Record outputs
outputs = np.array(data_combined['Status'])
# Drop the output columns
data_combined= data_combined.drop('Status', axis = 1)

In [18]:
data_combined = data_combined.fillna(0)
data_combined

,EngineeringSoldkWSize,EngineeringSoldAnnualkWh,EnergyConsumption,RoofSqFoot,NumMountingPlanes,NumPanels,UtilityCostPerKWh,OldBill,UtilityInflationRate,AverageShading,...,50090.0,90398.0,100099.0,998377099.0,998467098.0,998469099.0,998504099.0,Above Two Stories,One Story,Two Stories
0,3.465,3806.0090,8860.0,1508.0,1,11,0.113579,134.1167,0.0380,1.200000e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,13.860,18115.3150,62233.0,2518.0,4,44,0.193729,1056.3469,0.0290,4.363636e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,3.780,4887.0342,7464.0,1980.0,3,12,0.152606,146.5714,0.0290,1.708333e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,16.065,23229.5524,23834.0,3155.0,3,51,0.330294,704.0654,0.0290,8.823529e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10.920,14676.4759,18131.0,6512.0,2,42,0.298678,499.3237,0.0290,8.571429e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,4.095,4089.5730,6483.0,0.0,2,13,0.203558,158.0187,0.0290,3.430769e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,6.500,8025.7797,8094.0,3673.0,2,25,0.185493,170.7077,0.0290,9.304348e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8.505,12196.6609,12409.0,2976.0,2,27,0.264252,321.3057,0.0290,5.312500e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,5.035,6701.9949,8706.0,2515.0,3,19,0.178033,177.2094,0.0290,6.684210e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,3.190,4972.2416,6270.0,2672.0,1,11,0.215150,162.0934,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10,6.760,9105.3562,6073.0,3808.0,3,26,0.221312,161.6801,0.0290,1.384615e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12.285,17330.0570,14083.0,5085.0,3,39,0.297326,396.2484,0.0290,5.076923e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,4.940,7258.3906,7737.0,3313.0,1,19,0.240437,202.3337,0.0290,3.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13,5.670,8232.7560,7759.0,2050.0,2,18,0.213104,185.8362,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14,3.120,4796.0282,5782.0,2687.0,1,12,0.204045,145.6279,0.0290,7.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,3.780,4564.8981,3232.0,2360.0,1,12,0.183530,96.7428,0.0290,2.500000e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,4.420,6145.4131,6179.0,0.0,1,17,0.228446,165.6774,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,5.200,7962.6714,7893.0,3085.0,1,20,0.204619,182.6349,0.0290,6.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,9.360,10211.3899,10468.0,2823.0,2,36,0.249508,265.7006,0.0290,2.191667e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,11.960,17779.8213,18021.0,3424.0,1,46,0.242077,411.5859,0.0290,1.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,3.380,5426.3984,7011.0,1779.0,1,13,0.183319,155.1507,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,7.540,11101.8507,12372.0,2211.0,3,29,0.125626,187.4399,0.0350,3.793103e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
22,8.320,13414.6050,13843.0,1898.0,1,32,0.124223,201.2214,0.0350,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,6.300,6945.7718,10579.0,3266.0,1,20,0.125500,168.5582,0.0350,2.900000e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,5.830,7876.8480,13876.0,4080.0,3,22,0.123423,200.6377,0.0350,1.345455e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,6.500,9806.5233,9814.0,2241.0,1,25,0.157797,129.0520,0.0350,4.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,4.420,6611.9272,6683.0,2048.0,1,17,0.156157,146.0058,0.0350,6.250000e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,10.400,11638.5966,18696.0,2573.0,3,40,0.130556,256.2393,0.0190,1.640000e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
28,8.060,10895.4147,13630.0,2228.0,2,31,0.136676,208.0739,0.0190,1.110000e-16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
29,9.880,9913.7115,18068.0,3600.0,3,38,0.226433,393.7659,0.0190,2.905263e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19970,2.600,3016.1384,5379.0,1431.0,1,8,0.226230,169.5335,0.0330,1.700000e-01,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19971,6.300,7530.9149,3534.0,2126.0,2,21,0.244855,72.1099,0.0330,7.428571e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19972,6.175,6965.1098,7220.0,1546.0,2,19,0.218361,199.5061,0.0330,0.000000e+00,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19973,4.800,6074.7440,6000.0,1124.0,1,16,0.195307,149.4517,0.0350,3.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19974,4.500,3504.2617,3985.0,1653.0,1,15,0.192480,115.7179,0.0350,3.638462e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
19975,6.825,9043.2696,1961.0,2248.0,2,21,0.289051,47.2358,0.0540,-2.220000e-16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19976,6.600,6777.6014,7116.0,1814.0,2,22,0.203592,172.5285,0.0540,9.545455e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19977,6.900,6398.4374,7590.0,3202.0,1,23,0.225615,142.7016,0.0290,1.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19978,4.200,5372.9069,5464.0,2140.0,1,14,0.185564,138.4517,0.0372,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19979,4.550,3805.8178,7491.0,1161.0,2,14,0.219350,188.7276,0.0400,2.728571e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19980,6.300,7359.8484,7177.0,2008.0,1,21,0.219655,183.1703,0.0400,1.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19981,3.900,4313.5776,12286.0,1508.0,3,12,0.216322,273.2764,0.0400,3.083333e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19982,5.400,8246.3844,8973.0,2569.0,2,18,0.255705,240.8811,0.0290,5.000000e-03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19983,15.300,16420.0074,28315.0,7582.0,3,51,0.323261,810.0727,0.0290,1.029412e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19984,7.800,11158.5333,9405.0,2446.0,2,24,0.272656,264.1292,0.0290,6.750000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19985,6.300,8092.6628,7759.0,2355.0,1,21,0.266938,223.0326,0.0290,2.100000e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19986,4.875,6676.7984,6477.0,1974.0,2,15,0.244269,181.7585,0.0290,4.200000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
19987,5.200,8086.0211,7739.0,2246.0,2,16,0.238332,153.7041,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19988,6.500,11023.3981,9207.0,3671.0,2,20,0.244357,187.4828,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19989,2.100,3158.4299,3179.0,3357.0,1,7,0.210778,55.8387,0.0290,1.585714e-01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19990,15.900,22973.4024,24190.0,7017.0,5,53,0.327962,711.0314,0.0290,1.830189e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19991,3.900,6353.3810,3837.0,2908.0,1,12,0.227667,122.7107,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19992,13.325,20839.8881,21034.0,2847.0,3,41,0.283482,544.9438,0.0290,2.243902e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19993,12.675,15304.5161,25244.0,3525.0,5,39,0.313400,706.6007,0.0290,6.282051e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19994,4.875,6432.2248,7473.0,1546.0,2,15,0.229478,190.9544,0.0290,4.333333e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19995,5.850,8993.4713,7354.0,1946.0,3,18,0.249353,202.7260,0.0290,6.833333e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
19996,15.275,20416.4615,28250.0,6843.0,5,47,0.205299,530.6196,0.0290,4.425532e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19997,6.500,9085.0457,9427.0,3243.0,1,20,0.099264,77.9804,0.0290,8.000000e-02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19998,15.900,16110.6959,22092.0,2160.0,7,53,0.131961,242.9398,0.0337,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19999,6.500,7114.5657,9225.0,1379.0,3,20,0.201033,154.5442,0.0290,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
# Saving feature names for later use
feature_list = list(data_combined.columns)
feature_list

['EngineeringSoldkWSize',
 'EngineeringSoldAnnualkWh',
 'EnergyConsumption',
 'RoofSqFoot',
 'NumMountingPlanes',
 'NumPanels',
 'UtilityCostPerKWh',
 'OldBill',
 'UtilityInflationRate',
 'AverageShading',
 'AZ',
 'CA',
 'CO',
 'CT',
 'DC',
 'DE',
 'FL',
 'HI',
 'MA',
 'MD',
 'NH',
 'NJ',
 'NM',
 'NV',
 'NY',
 'OR',
 'PA',
 'RI',
 'SC',
 'TX',
 'UT',
 'VA',
 'VT',
 1001.0,
 1002.0,
 1007.0,
 1027.0,
 1028.0,
 1033.0,
 1035.0,
 1038.0,
 1056.0,
 1057.0,
 1060.0,
 1066.0,
 1073.0,
 1077.0,
 1082.0,
 1088.0,
 1089.0,
 1104.0,
 1106.0,
 1107.0,
 1109.0,
 1118.0,
 1119.0,
 1128.0,
 1129.0,
 1201.0,
 1220.0,
 1222.0,
 1224.0,
 1225.0,
 1226.0,
 1230.0,
 1237.0,
 1238.0,
 1247.0,
 1254.0,
 1267.0,
 1301.0,
 1331.0,
 1351.0,
 1364.0,
 1370.0,
 1373.0,
 1375.0,
 1420.0,
 1432.0,
 1440.0,
 1452.0,
 1453.0,
 1462.0,
 1463.0,
 1464.0,
 1469.0,
 1473.0,
 1474.0,
 1475.0,
 1501.0,
 1507.0,
 1510.0,
 1516.0,
 1520.0,
 1523.0,
 1525.0,
 1527.0,
 1532.0,
 1534.0,
 1536.0,
 1540.0,
 1543.0,
 1550.0,
 1562.0,
 1568.0,
 1569.0,
 1570.0,
 1581.0,
 1602.0,
 1604.0,
 1605.0,
 1606.0,
 1609.0,
 1610.0,
 1701.0,
 1702.0,
 1720.0,
 1721.0,
 1730.0,
 1746.0,
 1747.0,
 1748.0,
 1752.0,
 1754.0,
 1756.0,
 1757.0,
 1760.0,
 1772.0,
 1773.0,
 1776.0,
 1778.0,
 1801.0,
 1803.0,
 1810.0,
 1821.0,
 1824.0,
 1826.0,
 1827.0,
 1830.0,
 1841.0,
 1843.0,
 1844.0,
 1845.0,
 1850.0,
 1851.0,
 1852.0,
 1876.0,
 1879.0,
 1886.0,
 1890.0,
 1902.0,
 1904.0,
 1905.0,
 1906.0,
 1907.0,
 1913.0,
 1922.0,
 1950.0,
 1952.0,
 1970.0,
 1984.0,
 2019.0,
 2021.0,
 2026.0,
 2035.0,
 2038.0,
 2050.0,
 2053.0,
 2054.0,
 2056.0,
 2066.0,
 2067.0,
 2072.0,
 2090.0,
 2121.0,
 2124.0,
 2125.0,
 2126.0,
 2128.0,
 2130.0,
 2131.0,
 2132.0,
 2135.0,
 2136.0,
 2138.0,
 2143.0,
 2144.0,
 2145.0,
 2148.0,
 2149.0,
 2150.0,
 2151.0,
 2155.0,
 2169.0,
 2170.0,
 2171.0,
 2176.0,
 2186.0,
 2189.0,
 2190.0,
 2301.0,
 2302.0,
 2322.0,
 2324.0,
 2333.0,
 2338.0,
 2339.0,
 2341.0,
 2347.0,
 2351.0,
 2360.0,
 2364.0,
 2368.0,
 2370.0,
 2382.0,
 2420.0,
 2451.0,
 2452.0,
 2453.0,
 2459.0,
 2465.0,
 2467.0,
 2472.0,
 2474.0,
 2476.0,
 2492.0,
 2493.0,
 2494.0,
 2532.0,
 2536.0,
 2537.0,
 2561.0,
 2562.0,
 2563.0,
 2571.0,
 2576.0,
 2601.0,
 2631.0,
 2632.0,
 2641.0,
 2642.0,
 2644.0,
 2645.0,
 2646.0,
 2648.0,
 2649.0,
 2650.0,
 2651.0,
 2652.0,
 2653.0,
 2660.0,
 2664.0,
 2666.0,
 2667.0,
 2668.0,
 2702.0,
 2703.0,
 2715.0,
 2717.0,
 2718.0,
 2719.0,
 2720.0,
 2721.0,
 2723.0,
 2724.0,
 2725.0,
 2726.0,
 2740.0,
 2743.0,
 2744.0,
 2745.0,
 2747.0,
 2748.0,
 2762.0,
 2764.0,
 2766.0,
 2767.0,
 2769.0,
 2770.0,
 2771.0,
 2777.0,
 2779.0,
 2780.0,
 2790.0,
 2804.0,
 2809.0,
 2814.0,
 2816.0,
 2817.0,
 2818.0,
 2825.0,
 2826.0,
 2828.0,
 2833.0,
 2837.0,
 2840.0,
 2842.0,
 2857.0,
 2860.0,
 2861.0,
 2863.0,
 2864.0,
 2865.0,
 2871.0,
 2874.0,
 2878.0,
 2879.0,
 2885.0,
 2886.0,
 2888.0,
 2889.0,
 2891.0,
 2892.0,
 2893.0,
 2898.0,
 2904.0,
 2905.0,
 2906.0,
 2908.0,
 2909.0,
 2910.0,
 2914.0,
 2915.0,
 2916.0,
 2919.0,
 2920.0,
 2921.0,
 3031.0,
 3032.0,
 3044.0,
 3046.0,
 3047.0,
 3051.0,
 3053.0,
 3054.0,
 3055.0,
 3060.0,
 3062.0,
 3063.0,
 3070.0,
 3071.0,
 3082.0,
 3087.0,
 3102.0,
 3104.0,
 3109.0,
 3110.0,
 3220.0,
 3237.0,
 3246.0,
 3258.0,
 3269.0,
 3281.0,
 3303.0,
 3307.0,
 3431.0,
 3447.0,
 3451.0,
 3462.0,
 3801.0,
 3819.0,
 3820.0,
 3824.0,
 3826.0,
 3833.0,
 3840.0,
 3841.0,
 3848.0,
 3856.0,
 3857.0,
 3867.0,
 3878.0,
 5001.0,
 5032.0,
 5040.0,
 5042.0,
 5068.0,
 5146.0,
 5158.0,
 5201.0,
 5250.0,
 5252.0,
 5261.0,
 5301.0,
 5346.0,
 5354.0,
 5403.0,
 5404.0,
 5408.0,
 5440.0,
 5443.0,
 5444.0,
 5445.0,
 5446.0,
 5451.0,
 5452.0,
 5454.0,
 5455.0,
 5456.0,
 5457.0,
 5458.0,
 5459.0,
 5461.0,
 5464.0,
 5465.0,
 5468.0,
 5472.0,
 5477.0,
 5478.0,
 5482.0,
 5486.0,
 5487.0,
 5488.0,
 5489.0,
 5491.0,
 5494.0,
 5495.0,
 5602.0,
 5641.0,
 5654.0,
 5667.0,
 5673.0,
 5676.0,
 5677.0,
 5679.0,
 5701.0,
 5733.0,
 5735.0,
 5744.0,
 5753.0,
 5759.0,
 5762.0,
 5763.0,
 5765.0,
 5767.0,
 5769.0,
 5773.0,
 5777.0,
 6002.0,
 6010.0,
 6019.0,
 6026.0,
 6029.0,
 6033.0,
 6035.0,
 6037.0,
 6039.0,
 6040.0,
 6051.0,
 6053.0,
 6058.0,
 6062.0,
 6063.0,
 6066.0,
 6067.0,
 6069.0,
 6074.0,
 6076.0,
 6082.0,
 6084.0,
 6088.0,
 6095.0,
 6096.0,
 6106.0,
 6107.0,
 6108.0,
 6109.0,
 6110.0,
 6111.0,
 6112.0,
 6114.0,
 6117.0,
 6118.0,
 6119.0,
 6226.0,
 6234.0,
 6237.0,
 6238.0,
 6239.0,
 6254.0,
 6255.0,
 6259.0,
 6260.0,
 6278.0,
 6279.0,
 6280.0,
 6320.0,
 6339.0,
 6340.0,
 6351.0,
 6354.0,
 6355.0,
 6359.0,
 6370.0,
 6371.0,
 6374.0,
 6375.0,
 6377.0,
 6379.0,
 6382.0,
 6385.0,
 6401.0,
 6405.0,
 6410.0,
 6413.0,
 6415.0,
 6416.0,
 6417.0,
 6418.0,
 6420.0,
 6424.0,
 6437.0,
 6441.0,
 6442.0,
 6443.0,
 6450.0,
 6451.0,
 6457.0,
 6460.0,
 6468.0,
 6469.0,
 6470.0,
 6471.0,
 6473.0,
 6477.0,
 6478.0,
 6479.0,
 6480.0,
 6483.0,
 6484.0,
 6488.0,
 6489.0,
 6511.0,
 6512.0,
 6513.0,
 6514.0,
 6515.0,
 6516.0,
 6517.0,
 6518.0,
 6524.0,
 6525.0,
 6604.0,
 6605.0,
 6606.0,
 6610.0,
 6611.0,
 6614.0,
 6615.0,
 6704.0,
 6705.0,
 6708.0,
 6716.0,
 6751.0,
 6756.0,
 6759.0,
 6770.0,
 6776.0,
 6779.0,
 6783.0,
 6784.0,
 6787.0,
 6790.0,
 6795.0,
 6798.0,
 6801.0,
 6804.0,
 6810.0,
 6811.0,
 6812.0,
 6824.0,
 6825.0,
 6850.0,
 6877.0,
 6880.0,
 6883.0,
 6902.0,
 7002.0,
 7003.0,
 7005.0,
 7006.0,
 7008.0,
 7009.0,
 7011.0,
 7013.0,
 7017.0,
 7018.0,
 7020.0,
 7026.0,
 7027.0,
 7031.0,
 7032.0,
 7036.0,
 7039.0,
 7040.0,
 7043.0,
 7047.0,
 7050.0,
 7052.0,
 7054.0,
 7058.0,
 7060.0,
 7065.0,
 7067.0,
 7070.0,
 7071.0,
 7076.0,
 7080.0,
 7083.0,
 7090.0,
 7094.0,
 7095.0,
 7109.0,
 7110.0,
 7111.0,
 7201.0,
 7202.0,
 7203.0,
 7204.0,
 7205.0,
 7206.0,
 7208.0,
 7304.0,
 7305.0,
 7306.0,
 7410.0,
 7463.0,
 7465.0,
 7470.0,
 7480.0,
 7502.0,
 7504.0,
 7604.0,
 7607.0,
 7621.0,
 7631.0,
 7632.0,
 7642.0,
 7647.0,
 7652.0,
 7657.0,
 7661.0,
 7666.0,
 7675.0,
 7704.0,
 7716.0,
 7724.0,
 7727.0,
 7728.0,
 7730.0,
 7734.0,
 7735.0,
 7739.0,
 7746.0,
 7747.0,
 7751.0,
 7753.0,
 7757.0,
 7764.0,
 7801.0,
 7840.0,
 7853.0,
 7860.0,
 7863.0,
 7866.0,
 7869.0,
 7882.0,
 7922.0,
 7940.0,
 7974.0,
 8002.0,
 8003.0,
 8004.0,
 8005.0,
 8007.0,
 8009.0,
 8010.0,
 8012.0,
 8015.0,
 8016.0,
 8018.0,
 8021.0,
 8027.0,
 8028.0,
 8030.0,
 8031.0,
 8033.0,
 8036.0,
 8037.0,
 8043.0,
 8045.0,
 8046.0,
 8050.0,
 8051.0,
 8052.0,
 8053.0,
 8054.0,
 8055.0,
 8056.0,
 8057.0,
 8059.0,
 8060.0,
 8061.0,
 8062.0,
 8063.0,
 8066.0,
 8069.0,
 8070.0,
 8071.0,
 8075.0,
 8077.0,
 8078.0,
 8080.0,
 8081.0,
 8083.0,
 8084.0,
 8085.0,
 8087.0,
 8088.0,
 8089.0,
 8090.0,
 8091.0,
 8093.0,
 8094.0,
 8096.0,
 8097.0,
 8105.0,
 8106.0,
 8107.0,
 8108.0,
 8109.0,
 8110.0,
 8201.0,
 8203.0,
 8204.0,
 8205.0,
 8210.0,
 8215.0,
 8223.0,
 8225.0,
 8226.0,
 8230.0,
 8232.0,
 8234.0,
 8240.0,
 8244.0,
 8251.0,
 8252.0,
 8260.0,
 8302.0,
 8312.0,
 8319.0,
 8322.0,
 8330.0,
 8332.0,
 8344.0,
 8352.0,
 8360.0,
 8361.0,
 8401.0,
 8512.0,
 8515.0,
 8518.0,
 8520.0,
 8525.0,
 8527.0,
 8535.0,
 8540.0,
 8610.0,
 8619.0,
 8620.0,
 8629.0,
 8638.0,
 8648.0,
 8690.0,
 8722.0,
 8723.0,
 8724.0,
 8742.0,
 8753.0,
 8757.0,
 8759.0,
 8805.0,
 8807.0,
 8812.0,
 8816.0,
 8817.0,
 8820.0,
 8822.0,
 8830.0,
 8831.0,
 8840.0,
 8844.0,
 8848.0,
 8852.0,
 8854.0,
 8861.0,
 8863.0,
 8865.0,
 8869.0,
 8872.0,
 8873.0,
 8876.0,
 8901.0,
 8902.0,
 10306.0,
 10310.0,
 10312.0,
 10314.0,
 10473.0,
 10502.0,
 10505.0,
 10509.0,
 10514.0,
 10537.0,
 10538.0,
 10541.0,
 10548.0,
 10549.0,
 10560.0,
 10562.0,
 10566.0,
 10567.0,
 10573.0,
 10583.0,
 10591.0,
 10595.0,
 10596.0,
 10598.0,
 10605.0,
 10607.0,
 10701.0,
 10703.0,
 10704.0,
 10705.0,
 10706.0,
 10707.0,
 10709.0,
 10710.0,
 10804.0,
 10805.0,
 10901.0,
 10916.0,
 10918.0,
 10920.0,
 10923.0,
 10924.0,
 10925.0,
 10927.0,
 10940.0,
 10941.0,
 10950.0,
 10952.0,
 10954.0,
 10956.0,
 10960.0,
 10962.0,
 10973.0,
 10977.0,
 10980.0,
 10983.0,
 10984.0,
 10986.0,
 10989.0,
 10990.0,
 10992.0,
 10994.0,
 11001.0,
 11003.0,
 11010.0,
 11510.0,
 11516.0,
 11518.0,
 11545.0,
 11552.0,
 11553.0,
 11554.0,
 11557.0,
 11561.0,
 11563.0,
 11565.0,
 11566.0,
 11570.0,
 11572.0,
 11575.0,
 11580.0,
 11581.0,
 11590.0,
 11596.0,
 11598.0,
 11701.0,
 11703.0,
 11704.0,
 11706.0,
 11710.0,
 11713.0,
 11714.0,
 11716.0,
 11717.0,
 11722.0,
 11725.0,
 11726.0,
 11727.0,
 11729.0,
 11730.0,
 11731.0,
 11735.0,
 11740.0,
 11741.0,
 11743.0,
 11746.0,
 11749.0,
 11751.0,
 11752.0,
 11753.0,
 11754.0,
 11756.0,
 11757.0,
 11758.0,
 11763.0,
 11766.0,
 11768.0,
 11772.0,
 11777.0,
 11778.0,
 11779.0,
 11783.0,
 11784.0,
 11787.0,
 11788.0,
 11792.0,
 11793.0,
 11795.0,
 11798.0,
 11801.0,
 11803.0,
 11901.0,
 11930.0,
 11934.0,
 11935.0,
 11937.0,
 11946.0,
 11949.0,
 11950.0,
 11951.0,
 11953.0,
 11961.0,
 11967.0,
 11980.0,
 12010.0,
 12015.0,
 12020.0,
 12033.0,
 12037.0,
 12047.0,
 12052.0,
 12054.0,
 12065.0,
 12068.0,
 12074.0,
 12078.0,
 12086.0,
 12090.0,
 12095.0,
 12110.0,
 12116.0,
 12117.0,
 12118.0,
 12122.0,
 12123.0,
 12134.0,
 12140.0,
 12144.0,
 12155.0,
 12157.0,
 12158.0,
 12159.0,
 12168.0,
 12175.0,
 12180.0,
 12182.0,
 12185.0,
 12188.0,
 12189.0,
 12196.0,
 12202.0,
 12203.0,
 12204.0,
 12205.0,
 12208.0,
 12209.0,
 12211.0,
 12302.0,
 12303.0,
 12304.0,
 12305.0,
 12306.0,
 12307.0,
 12308.0,
 12309.0,
 ...]

In [20]:
# Convert to numpy array
data_combined = np.array(data_combined)

In [21]:
outputs

array([1, 1, 1, ..., 0, 0, 0])

In [22]:
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(data_combined, outputs, 
                                                                            test_size = 0.25, random_state = 1)

In [23]:
adaRF = AdaBoostClassifier(n_estimators=1000, random_state = 8001)
adaRF.fit(train_features, train_labels)
predictions = adaRF.predict(test_features)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        predictions[i] = 1
    else:
        predictions[i] = 0
errors = float(sum(abs(predictions - test_labels)))/len(test_labels)
errors

KeyboardInterrupt:

In [ ]:
get_importance(adaRF)

In [23]:
rf = RandomForestRegressor(n_estimators = 3000, random_state = 8001)

# Training
rf.fit(train_features, train_labels)
# Make predictions and determine the error
predictions = rf.predict(test_features)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        predictions[i] = 1
    else:
        predictions[i] = 0
errors = sum(abs(predictions - test_labels))/len(test_labels)
errors

0.28000000000000003

In [24]:
get_graph(rf)
get_importance(rf)

Variable: CA                   Importance: 0.29
Variable: RoofSqFoot           Importance: 0.07
Variable: UtilityCostPerKWh    Importance: 0.06
Variable: AverageShading       Importance: 0.06
Variable:          998504487.0 Importance: 0.06
Variable: EnergyConsumption    Importance: 0.05
Variable:              40003.0 Importance: 0.05
Variable: EngineeringSoldAnnualkWh Importance: 0.04
Variable: OldBill              Importance: 0.04
Variable: EngineeringSoldkWSize Importance: 0.03
Variable: NumPanels            Importance: 0.03
Variable:                100.0 Importance: 0.03
Variable:            9991227.0 Importance: 0.03
Variable:              10000.0 Importance: 0.02
Variable:              10800.0 Importance: 0.02
Variable: NumMountingPlanes    Importance: 0.01
Variable: UtilityInflationRate Importance: 0.01
Variable:          998504540.0 Importance: 0.01
Variable:                 90.0 Importance: 0.01
Variable:              20400.0 Importance: 0.01
Variable:             100099.0 Importance: 0.01
Variable:          998504099.0 Importance: 0.01
Variable: CT                   Importance: 0.01
Variable: OR                   Importance: 0.01
Variable:                 10.0 Importance: 0.0
Variable:                 15.0 Importance: 0.0
Variable:                 46.0 Importance: 0.0
Variable:                200.0 Importance: 0.0
Variable:                217.0 Importance: 0.0
Variable:                300.0 Importance: 0.0
Variable:                400.0 Importance: 0.0
Variable:               2601.0 Importance: 0.0
Variable:               4901.0 Importance: 0.0
Variable:              10304.0 Importance: 0.0
Variable:              20000.0 Importance: 0.0
Variable:              20004.0 Importance: 0.0
Variable:              40370.0 Importance: 0.0
Variable:              50001.0 Importance: 0.0
Variable:              80001.0 Importance: 0.0
Variable:             999454.0 Importance: 0.0
Variable:             999467.0 Importance: 0.0
Variable:            9982580.0 Importance: 0.0
Variable:            9991205.0 Importance: 0.0
Variable:            9991216.0 Importance: 0.0
Variable:            9991221.0 Importance: 0.0
Variable:            9991238.0 Importance: 0.0
Variable:            9991239.0 Importance: 0.0
Variable:            9991416.0 Importance: 0.0
Variable:            9991586.0 Importance: 0.0
Variable:            9991621.0 Importance: 0.0
Variable:            9991698.0 Importance: 0.0
Variable:            9991700.0 Importance: 0.0
Variable:            9992129.0 Importance: 0.0
Variable:          998504164.0 Importance: 0.0
Variable:          998504240.0 Importance: 0.0
Variable:          998504247.0 Importance: 0.0
Variable:          998504338.0 Importance: 0.0
Variable:          998504348.0 Importance: 0.0
Variable:          998504358.0 Importance: 0.0
Variable:          998504368.0 Importance: 0.0
Variable:          998504370.0 Importance: 0.0
Variable:          998504373.0 Importance: 0.0
Variable:          998504447.0 Importance: 0.0
Variable:          998504493.0 Importance: 0.0
Variable:          998504494.0 Importance: 0.0
Variable:          998504552.0 Importance: 0.0
Variable:          998504614.0 Importance: 0.0
Variable:          998504726.0 Importance: 0.0
Variable:          998504737.0 Importance: 0.0
Variable:          998504750.0 Importance: 0.0
Variable:          998504775.0 Importance: 0.0
Variable:                490.0 Importance: 0.0
Variable:              49601.0 Importance: 0.0
Variable:              50090.0 Importance: 0.0
Variable:          998467098.0 Importance: 0.0
Variable: AZ                   Importance: 0.0
Variable: CO                   Importance: 0.0
Variable: FL                   Importance: 0.0
Variable: MA                   Importance: 0.0
Variable: MD                   Importance: 0.0
Variable: NJ                   Importance: 0.0
Variable: NV                   Importance: 0.0
Variable: NY                   Importance: 0.0
Variable: PA                   Importance: 0.0
Variable: RI                   Importance: 0.0
Variable: TX                   Importance: 0.0
Variable: VT                   Importance: 0.0

In [51]:
# n_est = np.linspace(100,2000,20, dtype="int")
# error_list = list()
# for n in n_est:
#     # Instantiate model with n decision trees
#     rf = RandomForestRegressor(n_estimators = n, random_state = 8001)
#     # rf = RandomForestRegressor(n_estimators = 1000, random_state = 42, max_depth=3)
    
#     # Training
#     rf.fit(train_features, train_labels)
#     # Make predictions and determine the error
#     predictions = rf.predict(test_features)
#     for i in range(len(predictions)):
#         if predictions[i] >= 0.5:
#             predictions[i] = 1
#         else:
#             predictions[i] = 0
#     errors = sum(abs(predictions - test_labels))/len(test_labels)
#     error_list.append(errors)
#     # Print out the mean absolute error (mae)
# #     print('Mean Absolute Error:', round(np.mean(errors), 2))
# plt.figure(10, figsize=(15,8))
# plt.plot(n_est, error_list)
# plt.xlabel("# of estimators in RF")
# plt.ylabel("Ratio of errors")
# plt.title("Error Curve")
# plt.xticks(n_est)

KeyboardInterrupt:

In [26]:
# New random forest with only the two most important variables
rf_most_important = RandomForestRegressor(n_estimators= 1000, random_state=8001)
# Extract the two most important features
important_indices = [feature_list.index('GasRatePlanID'), feature_list.index('UtilityRatePlanId')]
train_important = train_features[:, important_indices]
test_important = test_features[:, important_indices]
# Train the random forest
rf_most_important.fit(train_important, train_labels)
# Make predictions and determine the error
predictions = rf_most_important.predict(test_important)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        predictions[i] = 1
    else:
        predictions[i] = 0
errors = sum(abs(predictions - test_labels))/len(test_labels)
# Display the performance metrics
print('Mean Absolute Error:', round(np.mean(errors), 2))

('Mean Absolute Error:', 0.22)

In [ ]:
data_combined[sample_install, :]